//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessment
    {
        public int AssessmentID { get; set; }
        public Nullable<int> ParentAssessmentID { get; set; }
        public Nullable<bool> Header { get; set; }
        public Nullable<int> HeaderID { get; set; }
        public Nullable<bool> Composite { get; set; }
        public Nullable<bool> SubAssessment { get; set; }
        public string Name { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public string AssessmentCode { get; set; }
        public Nullable<float> MaximumScore { get; set; }
        public Nullable<int> DecimalPoints { get; set; }
        public string AccessLevelRequired { get; set; }
        public Nullable<bool> AllowAttachments { get; set; }
        public Nullable<bool> StoreAttachments { get; set; }
        public string ExtendedDescription { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> NotesMaxLength { get; set; }
        public Nullable<bool> StudentReportItem { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> DefaultColour { get; set; }
        public Nullable<bool> ShowToParent { get; set; }
    }
}
