//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessmentresultvalue
    {
        public int ResultValueID { get; set; }
        public Nullable<int> ResultID { get; set; }
        public Nullable<int> ResultTypeID { get; set; }
        public string ResultValue { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public Nullable<bool> OfflineAdd { get; set; }
        public Nullable<bool> OfflineEdit { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
