//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessmentresulttype
    {
        public int AssessmentID { get; set; }
        public Nullable<int> ResultType { get; set; }
        public int ResultTypeID { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<bool> UseDefaultValues { get; set; }
        public Nullable<float> MinNumber { get; set; }
        public Nullable<float> MaxNumber { get; set; }
        public Nullable<int> DecimalPoints { get; set; }
        public string AllowedValues { get; set; }
        public Nullable<bool> Updated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> ShowToParent { get; set; }
        public Nullable<bool> ShowToParentGraph { get; set; }
        public Nullable<bool> FormattingEnabled { get; set; }
    }
}
