//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assessmentresultcalculated
    {
        public int ResultTypeCalcID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<float> ResultOrder { get; set; }
        public Nullable<int> CalculatedTypeID { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public Nullable<int> ResultTypeID1 { get; set; }
        public Nullable<int> ResultTypeID2 { get; set; }
        public Nullable<int> ResultTypeID3 { get; set; }
        public Nullable<int> ResultTypeID4 { get; set; }
        public Nullable<int> ResultTypeID5 { get; set; }
        public Nullable<int> ResultTypeID6 { get; set; }
        public Nullable<int> ResultTypeID7 { get; set; }
        public Nullable<int> ResultTypeID8 { get; set; }
        public Nullable<int> ResultTypeID9 { get; set; }
        public Nullable<int> ResultTypeID10 { get; set; }
        public Nullable<int> ResultTypeID11 { get; set; }
        public string Percentage { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<int> OperatorTypeID1 { get; set; }
        public string Value1 { get; set; }
        public Nullable<int> OperatorTypeID2 { get; set; }
        public string Value2 { get; set; }
        public Nullable<int> OperatorTypeID3 { get; set; }
        public string Value3 { get; set; }
        public Nullable<int> OperatorTypeID4 { get; set; }
        public string Value4 { get; set; }
        public string FinalResult { get; set; }
        public Nullable<int> FinalColour { get; set; }
        public string FinalValueToGraph { get; set; }
        public Nullable<int> ColumnAlignment { get; set; }
        public Nullable<int> ColumnWidth { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> FormattingEnabled { get; set; }
    }
}
