//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendancereason
    {
        public int ReasonID { get; set; }
        public string ReasonCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> CountToAbsenceTotals { get; set; }
    }
}
