//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GradexpertEntities : DbContext
    {
        public GradexpertEntities()
            : base("name=GradexpertEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesslevel> accesslevels { get; set; }
        public virtual DbSet<assessmentresultcalculated> assessmentresultcalculateds { get; set; }
        public virtual DbSet<assessmentresulttype> assessmentresulttypes { get; set; }
        public virtual DbSet<assessmentresultvalue> assessmentresultvalues { get; set; }
        public virtual DbSet<assessment> assessments { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<attendancereason> attendancereasons { get; set; }
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<indicator> indicators { get; set; }
        public virtual DbSet<mapdetail> mapdetails { get; set; }
        public virtual DbSet<mapheader> mapheaders { get; set; }
        public virtual DbSet<result> results { get; set; }
        public virtual DbSet<resulttype> resulttypes { get; set; }
        public virtual DbSet<studentclass> studentclasses { get; set; }
        public virtual DbSet<studentindicator> studentindicators { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<teacherclass> teacherclasses { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<usergroup> usergroups { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userselection> userselections { get; set; }
        public virtual DbSet<year> years { get; set; }
    }
}
