//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapdetail
    {
        public int MapDetailID { get; set; }
        public Nullable<int> MapHeaderID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> ResultTypeID { get; set; }
        public Nullable<int> ColourFormatType { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public Nullable<bool> EffectSize { get; set; }
        public Nullable<bool> Growth { get; set; }
        public Nullable<int> IndicatorID { get; set; }
        public Nullable<sbyte> TeacherNameRequired { get; set; }
        public Nullable<sbyte> AllowEdit { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> PageHeaderID { get; set; }
        public Nullable<int> IncludePreviousTerms { get; set; }
        public Nullable<int> IncludePreviousSemesters { get; set; }
        public string ResultTypeIDs { get; set; }
    }
}
