//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapheader
    {
        public int MapHeaderID { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public string Description { get; set; }
        public string ExtendedDescription { get; set; }
        public Nullable<bool> AvailableToAll { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Semester { get; set; }
        public Nullable<bool> HideHeaders { get; set; }
        public Nullable<int> Week { get; set; }
        public string UserIDs { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> DefaultReportLayoutID { get; set; }
        public Nullable<bool> OfflineEdit { get; set; }
        public Nullable<bool> OfflineAdd { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<int> MapGroupID { get; set; }
        public Nullable<bool> ShowStdDeviation { get; set; }
        public Nullable<bool> ShowMedian { get; set; }
        public Nullable<bool> ShowMean { get; set; }
    }
}
