//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resulttype
    {
        public int ResultTypeID { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ExtendedDescription { get; set; }
        public Nullable<bool> AllowNumber { get; set; }
        public Nullable<bool> AllowLetter { get; set; }
        public Nullable<bool> AllowAll { get; set; }
        public Nullable<bool> AgeLevel { get; set; }
        public Nullable<bool> SelectFromList { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<float> MinNumber { get; set; }
        public Nullable<float> MaxNumber { get; set; }
        public Nullable<int> DecimalPoints { get; set; }
        public string AllowedValues { get; set; }
        public Nullable<int> ColumnAlignment { get; set; }
        public Nullable<int> ColumnWidth { get; set; }
        public Nullable<bool> Updated { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> FormattingEnabled { get; set; }
    }
}
