//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentclass
    {
        public int StudentID { get; set; }
        public int YearID { get; set; }
        public int ClassID { get; set; }
    }
}
