//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int studentID { get; set; }
        public string studentCode { get; set; }
        public string surname { get; set; }
        public string middlename { get; set; }
        public string firstname { get; set; }
        public string preferredname { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string notes { get; set; }
        public Nullable<bool> male { get; set; }
        public Nullable<bool> photopresent { get; set; }
        public Nullable<int> photosize { get; set; }
        public byte[] photo { get; set; }
        public Nullable<int> classID { get; set; }
        public Nullable<int> yearID { get; set; }
        public Nullable<bool> locked { get; set; }
        public string NotesLong { get; set; }
        public string NotesLong2 { get; set; }
        public Nullable<int> houseID { get; set; }
        public string StudentIndicators { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public Nullable<bool> OfflineEdit { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> ShowToParent { get; set; }
        public string Registration { get; set; }
    }
}
