//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentindicator
    {
        public int StudentIndicatorID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> IndicatorID { get; set; }
        public Nullable<int> SchoolID { get; set; }
    }
}
