//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacherclass
    {
        public int TeacherClassID { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Week { get; set; }
        public Nullable<int> Semester { get; set; }
    }
}
