//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usergroup
    {
        public int GroupID { get; set; }
        public string GroupDescription { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RowOrder { get; set; }
        public Nullable<bool> Header { get; set; }
        public Nullable<int> HeaderID { get; set; }
    }
}
