//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamraProfile.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FullName { get; set; }
        public string AccessLevel { get; set; }
        public Nullable<bool> LoggedIn { get; set; }
        public Nullable<System.DateTime> LoggedInDateTime { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> AllowOffline { get; set; }
        public string ClassList { get; set; }
        public string HeaderList { get; set; }
        public string ClassListNew { get; set; }
        public string HeaderListNew { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string IndicatorListNew { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string Email { get; set; }
        public string ClassIDsForCurrentYear { get; set; }
        public string MailServerUsername { get; set; }
        public string MailServerPassword { get; set; }
        public Nullable<System.DateTime> LastSettingsRefreshed { get; set; }
    }
}
